POST http://localhost:8088/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "b7c2089d-55f5-40b0-953d-db1deee3e9fd"

> {% client.global.set("auth_token", response.body.data.token) %}}

###

GET http://localhost:8088/admin/auth
Content-Type: application/json
Authorization: Bearer{{auth_token}}